{{- if and .Values.recgo_engine.persistence.enabled (not .Values.recgo_engine.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "recgo_engine.fullname" . }}
spec:
  accessModes:
    {{- range .Values.recgo_engine.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  {{- if .Values.recgo_engine.persistence.storageClass }}
  {{- if eq "-" .Values.recgo_engine.persistence.storageClassName }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.recgo_engine.persistence.storageClassName }}
  {{- end }}
  {{- end }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.recgo_engine.persistence.storage }}
{{- end }}