apiVersion: v1
kind: Service
metadata:
  name: {{ include "recgo-engine.fullname" . }}
  labels:
    {{- include "recgo-engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port.apiHTTPPort }}
      targetPort: 8080
      protocol: TCP
      name: api-http-port
    - port: {{ .Values.port.promePort }}
      targetPort: 8082
      protocol: TCP
      name: prome-port
  selector:
    {{- include "recgo-engine.selectorLabels" . | nindent 4 }}
