apiVersion: v1
kind: Service
metadata:
  name: {{ include "recgo_engine.fullname" . }}
  labels:
    {{- include "recgo_engine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.config.server.http_port }}
      targetPort: 8080
      protocol: TCP
      name: api-http-port
    - port: {{ .Values.config.server.prome_port }}
      targetPort: 8082
      protocol: TCP
      name: prome-port
  selector:
    {{- include "recgo_engine.selectorLabels" . | nindent 4 }}
