apiVersion: v1
kind: ConfigMap
metadata:
  name: recgo-engine-config
  namespace: uopensail
data:
  config.toml: |
    [server]
    project_name = "recgo_engine"
    grpc_port = {{ .Values.server.grpc_port }}
    http_port = {{ .Values.server.http_port }}
    prome_port = {{ .Values.server.prome_port }}
    pprof_port = {{ .Values.server.pprof_port }}
    debug = false

    [engine_data]
    url = "mock/data/enginedata"
    [ab]
    type = "growthbook"
    [ab.growthbook]
    api_host = "https://cdn.growthbook.io"
    client_key = "sdk-j3GcBo9yPzfDxFsA"

    [env]
    work_dir = "/data/data/recgo-engine"
    [env.finder]
    type = "local"
