apiVersion: v1
kind: Service
metadata:
  name: recgo-engine-service
  namespace: uopensail
  labels:
    app: recgo-engine
spec:
  selector:
    app: recgo-engine
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP