[server]
project_name = "recgo_engine"
grpc_port = 3527
http_port = 3528
prome_port = 3529
pprof_port = 3530
debug = true
[dbmodel]
url = "mock/data/enginedata"
[env]
work_dir = "/data/data/recgo-engine"
[env.finder]
type = "local"
